### ISSUE TITLE
Invalid SQL queries with hard-coded prefix

### ISSUE THREAD

**Issue by mudrd8mz** [marceloschmitt/moodle-block_telegram_forum#2]
```
            if ($DB->record_exists('block_telegram_forum', array('courseid' => $COURSE->id))) {
                $sql = "update mdl_block_telegram_forum set channel = $data->channelid where courseid = $COURSE->id";
                $DB->execute($sql);
            }
```

is not right. It is potentially vulnerable to SQL injection and fails on sites with other table prefix.

Ref: https://docs.moodle.org/dev/Plugin_contribution_checklist#Cross-DB_compatibility

**Comment by marceloschmitt** [comment]
Its true. I am sorry. I will correct today.

Marcelo Augusto Rauh Schmitt
marcelo.schmitt@poa.ifrs.edu.br

**Comment by mudrd8mz** [comment]
Alway use helper methods such as `$DB->update_record()` if possible. There should almost never be a need to use `execute()` method.

**Comment by marceloschmitt** [comment]
It was corrected.
