### ISSUE TITLE
lang file should only contain strings and no functions

### ISSUE THREAD

**Issue by danmarsden** [marceloschmitt/moodle-block_telegram_forum#4]
The translation tool used by Moodle (AMOS) will have issues with the "get_config()" calls in your lang file.

Please pass any extra variables using placeholders as per our guidelines here:
https://docs.moodle.org/dev/String_API#Run-time_parameters

Also - keep in mind that string concatentaion in the lang packs is also not allowed - it causes problems for the Moodle translation tool.

eg:
$string['test'] = "sometext"."somemoretext";
or
$string['test'] = "sometext".$string['someotheritem'];

each string must be contained within one set of quotes eg:
$string['test'] = "sometext somemoretext";

As this relates to AMOS/translation it is a blocker for approval in the plugins db.

**Comment by marceloschmitt** [comment]
Dan

Thanks a lot for all your messages. Today will be the day to fix everything that you sent.

Marcelo

**Comment by marceloschmitt** [comment]
Corrected language file:
$string['instructions'] = '1. Create a private channel in Telegram;  <BR>
                           2. Add {$a} as administrator of the channel; <BR>
                           3. Discover and copy the channel id; <BR>
                           4. Paste the channel id in the proper field; <BR>
                           5. Fill the channel link used for subscription.';

Corrected edit_form.php:
 $mform->addElement('static', 'description', get_string('instructionstitle', 'block_telegram_forum'),
            get_string('instructions', 'block_telegram_forum', get_config('block_telegram_forum', 'bot')));
