### ISSUE TITLE
Inccorrect use of curl_init

### ISSUE THREAD

**Issue by danmarsden** [marceloschmitt/moodle-block_telegram_forum#5]
Please don't initate curl_init() directly but use Moodle's own "curl" class which is a wrapper on PHP's curl functions.

Many organisations put their moodle site behind a web proxy and the internal curl wrapper takes care of this for you.

**Comment by danmarsden** [comment]
also - I'm not sure why you're setting CURLOPT_SSL_VERIFYPEER = false ? - surely telegram use a proper SSL cert on their end? - would be good to remove that as it's not great on security.

**Comment by marceloschmitt** [comment]
Solved, I think. I am using now:

 $curl = new curl();
        $url = $website . '/sendMessage';
        $result = $curl->get($url, $params);
        return true;
